image: Visual Studio 2017
version: '{branch}-{build}'

configuration:
- Release

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"

nuget:
  disable_publish_on_pr: true

before_build:
- nuget install Cake -ExcludeVersion

build_script:
- .\Cake\Cake.exe --target=PatchVersion --buildNumber=%APPVEYOR_BUILD_NUMBER% --currentBranch=%APPVEYOR_REPO_BRANCH% --pullRequestTitle="%APPVEYOR_PULL_REQUEST_TITLE%"
- .\Cake\Cake.exe --target=Restore
- .\Cake\Cake.exe --target=Build

test_script:
- .\Cake\Cake.exe --target=UnitTest

after_test:
- .\Cake\Cake.exe --target=Pack --pullRequestTitle="%APPVEYOR_PULL_REQUEST_TITLE%"

artifacts:
- path: out\*

deploy_script:
  - .\Cake\Cake.exe --target=Push --mygetApiKey=%MYGET_API_KEY% --nugetApiKey=%NUGET_API_KEY% --currentBranch=%APPVEYOR_REPO_BRANCH% --pullRequestTitle="%APPVEYOR_PULL_REQUEST_TITLE%"

